### ISSUE TITLE
Please provide LICENSE

### ISSUE THREAD

**Issue by remicollet** [theseer/DirectoryScanner#3]
Ca you please provides a LICENSE file in the pear package, with role="doc"

Fedora Packaging Guidelines requires (to respect the License term) that each RPM includes the LICENSE file, when provided by upstream, and to request for it when missing.

So I do.

http://fedoraproject.org/wiki/Packaging/LicensingGuidelines#License_Text

Please also consider adding the tests folder (with role="test"), will be usefull for downstream distribution.

**Comment by pedzed** [comment]
Just for additional info, this is the [New BSD License](https://en.wikipedia.org/wiki/BSD_licenses#3-clause_license_.28.22Revised_BSD_License.22.2C_.22New_BSD_License.22.2C_or_.22Modified_BSD_License.22.29).
