### ISSUE TITLE
No Documentation

### ISSUE THREAD

**Issue by Samshal** [theseer/DirectoryScanner#6]
Thanks for this resource but do you mind creating a readme or some documentation page?

**Comment by dotku** [comment]
@Samshal I'm asking the same question... I think you might want to fork and create one?

**Comment by theseer** [comment]
Sorry about that.
This project is quite old and I'm not even happy with the API design anymore. I was considering to rewrite it a few times but didn't find the motivation to actually do it.

Feel free to send a PR to add an actual readme, you'll find two examples on how to use it in the samples directory.
