### ISSUE TITLE
version 1.3.1 breaks artifact building on current bamboo version

### ISSUE THREAD

**Issue by EyesOnlyNet** [theseer/DirectoryScanner#7]
We use "theseer/phpdox" which have a dependency to "theseer/directoryscanner". 
On artifact creating our updated bamboo is yelling about the "vendor/theseer/directoryscanner/tests/_data/linkdir" because it is a symlink (and bamboo doesn't like that anymore).
We see that you have excluded the _linkdir_ file years ago. Can you please create a new tag with this changes in it? That would save us some workarounds.

**Comment by theseer** [comment]
Made a 1.3.2 release.

**Comment by EyesOnlyNet** [comment]
Thanks for that.
